// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -111);
    lv_obj_set_y(ui_Image1, 216);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 56);
    lv_obj_set_y(ui_Label1, -26);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Label1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Label1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Label1, ":))");

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 105);
    lv_obj_set_height(ui_Keyboard1, 59);
    lv_obj_set_x(ui_Keyboard1, -6);
    lv_obj_set_y(ui_Keyboard1, -2);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    uic_Label1 = ui_Label1;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image1 = NULL;
    uic_Label1 = NULL;
    ui_Label1 = NULL;
    ui_Keyboard1 = NULL;

}
